### ISSUE TITLE
Initial admin with theme and permissions

### ISSUE THREAD

**Issue by alexanmtz** [runkye/runkye-jornet#1]
### User story
As ADMINISTRATOR at Runkye platform, I want to have an administration system that allows the events creation, along with organizer to be shown at the Mobile app, so this admin will be used to manage the information that in the future will be used by the mobile app.

### Tasks

- [ ] Hello world with Rails and Postgres database running locally in a Postgres database
- [ ] Install Trestle gem
- [ ] Signin and Signup users
- [ ] Deploy to heroku

### Requirements

1. Rails
2. Postgres

You should run the project locally and then once you send the Pull Request, we will try to deploy on Heroku, and once is working we will approve.
